spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql : true
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: admin
    password: admin
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
